// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  // schema.prisma の場所
  schema: "./prisma/schema.prisma",

  // migrate の出力先（任意。指定しなくても動く）
  migrations: {
    path: "./prisma/migrations",
  },

  // ★ここに接続URLを書く（schema.prisma には書かない）
  datasource: {
    url: env("DATABASE_URL"),
  },
});