# 開発環境専用 - 本番環境では使用しないでください

services:
  db:
    image: postgres:16
    container_name: container_dev
    environment:
      POSTGRES_USER: gathers
      POSTGRES_PASSWORD: gathers
      POSTGRES_DB: DB_dev
    ports:
      - "5432:5432"
    volumes:
      - gathers_pgdata:/var/lib/postgresql/data

volumes:
  gathers_pgdata:
